

```
# Medida de Similaridade entre Textos
```



*   Neste Notebook, utilizaremos a função contaiment, Responsável por comparar dois textos e analisar a similaridade dos mesmos, com a relação aos seus n-gramas de interação.







```
# Contar N-Grama
```



*   palavras, Letras
*   Simbolos, Classificação gramatical e etc
 





In [1]:
import numpy as np
import sklearn

> Unigrama



In [2]:
from sklearn.feature_extraction.text import CountVectorizer

texto_comparado = "Um dia um adeus eu indo embora, com tanta loucura em meio a aventura"

texto_fonte = " Eu indo embora, Quanta loucura,Por tão pouca aventura,Agora entendo"

# Númeero de n_gramas
n = 1

#Instancia o contador de N-gramas
counts = CountVectorizer(analyzer='word', ngram_range=(n,n))

# Criando um dicionario de n-gramas
vocab2int = counts.fit([texto_comparado, texto_fonte]).vocabulary_

print(vocab2int)

{'um': 17, 'dia': 4, 'adeus': 0, 'eu': 8, 'indo': 9, 'embora': 6, 'com': 3, 'tanta': 15, 'loucura': 10, 'em': 5, 'meio': 11, 'aventura': 2, 'quanta': 14, 'por': 12, 'tão': 16, 'pouca': 13, 'agora': 1, 'entendo': 7}


> Bigrama

In [3]:
n = 2

counts = CountVectorizer(analyzer='word', ngram_range=(n,n))

vocab2int = counts.fit([texto_comparado, texto_fonte]).vocabulary_

print(vocab2int)

{'um dia': 19, 'dia um': 4, 'um adeus': 18, 'adeus eu': 0, 'eu indo': 8, 'indo embora': 9, 'embora com': 6, 'com tanta': 3, 'tanta loucura': 16, 'loucura em': 10, 'em meio': 5, 'meio aventura': 12, 'embora quanta': 7, 'quanta loucura': 15, 'loucura por': 11, 'por tão': 13, 'tão pouca': 17, 'pouca aventura': 14, 'aventura agora': 2, 'agora entendo': 1}


> Trigrama

In [4]:
n = 3


counts = CountVectorizer(analyzer='word', ngram_range=(n,n))

vocab2int = counts.fit([texto_comparado, texto_fonte]).vocabulary_

print(vocab2int)


{'um dia um': 18, 'dia um adeus': 3, 'um adeus eu': 17, 'adeus eu indo': 0, 'eu indo embora': 7, 'indo embora com': 8, 'embora com tanta': 5, 'com tanta loucura': 2, 'tanta loucura em': 15, 'loucura em meio': 10, 'em meio aventura': 4, 'indo embora quanta': 9, 'embora quanta loucura': 6, 'quanta loucura por': 14, 'loucura por tão': 11, 'por tão pouca': 12, 'tão pouca aventura': 16, 'pouca aventura agora': 13, 'aventura agora entendo': 1}


> Array de n-gramas

*   Vamos utilizar o CountVectorizer para criar um array com as contagens de n-gramas




In [7]:
#N-gramas

n = 1

#Instancia o contador de n-gramas
counts = CountVectorizer(analyzer='word', ngram_range=(n,n))

#Criar uma matriz de contagem de n=grama para dois textos
n_grams = counts.fit_transform([texto_comparado, texto_fonte])

#Criando um dicionário de n-gramas
vocab2int = counts.fit([texto_comparado, texto_fonte]).vocabulary_

n_grams_array = n_grams.toarray()

print('Vetor de n-gramas:\n\n', n_grams_array)

print()

print('Dicionario d en-gramas (unigrama):\n\n', vocab2int)


Vetor de n-gramas:

 [[1 0 1 1 1 1 1 0 1 1 1 1 0 0 0 1 0 2]
 [0 1 1 0 0 0 1 1 1 1 1 0 1 1 1 0 1 0]]

Dicionario d en-gramas (unigrama):

 {'um': 17, 'dia': 4, 'adeus': 0, 'eu': 8, 'indo': 9, 'embora': 6, 'com': 3, 'tanta': 15, 'loucura': 10, 'em': 5, 'meio': 11, 'aventura': 2, 'quanta': 14, 'por': 12, 'tão': 16, 'pouca': 13, 'agora': 1, 'entendo': 7}


In [8]:
n_grams

<2x18 sparse matrix of type '<class 'numpy.int64'>'
	with 23 stored elements in Compressed Sparse Row format>

In [10]:
n_grams.toarray()

array([[1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 2],
       [0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0]])

In [11]:
intersection_list = np.amin(n_grams.toarray(), axis=0)

intersection_list

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [12]:
intersection_count = np.sum(intersection_list)
intersection_count

5

In [13]:
index_A = 0

A_count = np.sum(n_grams.toarray()[index_A])
A_count

13

In [14]:
intersection_count/A_count

0.38461538461538464

> Criando uma função que recebe um array-de-gramas






In [18]:
def containment(n_grams_array):
  #Calcula o contaiment entre dois textos
  #Nomaliza a interseção dos contadores de n-gramas

  #Cria uma lista que contém o valor minimo encontrado nas colunas 
  #0 se não houver correspondências e 1+ para as palavras correspondentes

  intersection_list = np.amin(n_grams_array, axis= 0)

  #Soma numero de interseção

  intersection_count = np.sum(intersection_list)

  #Conta número de n-gramas no texto 1

  A_idx = 0
  A_count = np.sum(n_grams_array[A_idx])

  #Normaliza e calcula valor final

  containment_val = intersection_count/ A_count

  return containment_val

In [19]:
containment_val = containment(n_grams.toarray())

print('Containment: ', containment_val)

Containment:  0.38461538461538464


> Para Bigrama

In [21]:
#para n = n

counts_2grams = CountVectorizer(analyzer='word', ngram_range=(2,2))

bigram_counts = counts_2grams.fit_transform([texto_comparado,texto_fonte])

#Calcula Containment

containment_val = containment(bigram_counts.toarray())

print('Containment for n=2: ', containment_val)

Containment for n=2:  0.16666666666666666
